export const GET_FILE_FIELDS = 'GET_FIELD_FIELDS';
export const ADD_FILE_FIELD = 'ADD_FILE_FIELD';
export const RELOAD_FILE_FIELDS = 'RELOAD_FILE_FIELDS';
export const REMOVE_FILE_FIELD = 'REMOVE_FILE_FIELD';